version: '3'

services:
  srs:
    build: .
    container_name: cameras-ip-srs
    ports:
      - "1935:1935"  # RTMP
      - "1985:1985"  # HTTP API
      - "8080:8080"  # HTTP Server 
      - "8088:8088"  # HTTPS Server
    volumes:
      - ./logs:/usr/local/srs/objs/logs
      - ./recordings:/usr/local/srs/objs/nginx/html/dvr
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo 